name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  unit:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      
      - name: Build Artifact
        run: mvn --batch-mode clean verify

  integration:
    # Run on our custom runner.
    # Attention: paid runner, $0.064 per minute at the time of writing.
    # Not usable outside of this repo.
    runs-on: LinuxX64_16-cores_64GB
    # Set a max timeout of 20 minutes.
    # This way, we can control the cost of the runner.
    timeout-minutes: 20
    name: build and test
    # Run only if the unit-test job is successful
    needs: unit
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/\
          kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: Start minikube
        uses: medyagh/setup-minikube@master
      
      - name: Test cluster connection
        run: kubectl get pods -A
      
      - name: Setup Testing Environment
        run: |
          timeout 5m bash -c \
          'until \
          kustomize build ./src/test/resources/kubeflow-environment \
          | kubectl apply -f -; \
          do echo "Retrying to apply resources"; sleep 10; done'
      
      - name: Wait for deployments to be ready
        run: |
          kubectl wait --for=condition=available --timeout=300s \
          deployment --all --all-namespaces
      
      - name: Print deployment descriptions on failure
        if: failure()
        run: |
          kubectl get deployments -A
          kubectl describe deployments -A

      - name: Print pod descriptions on failure
        if: failure()
        run: |
          kubectl get pods -A
          kubectl describe pods -A
          
      - name: Run Spring Boot Integration Tests
        run: |
          mvn --batch-mode clean verify \
          -Dspring.profiles.active=integration
