name: Integration Testing

on:
  push:
    branches:
      - main
      - integration-tests
  pull_request:
    branches:
      - main

jobs:
  execute:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Test cluster connection
        run: kubectl get pods -A
      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          kustomize version
      - name: Setup Testing Environment
        run: |
          set -e

          kustomize build ./integration-tests/environment | kubectl apply -f -

          echo "Waiting for all deployments to be ready"
          kubectl wait --for=condition=available --timeout=600s deployment --all --all-namespaces
      - name: Get all pods
        run: |
          kubectl get po -A
